Update cve-2019-19781_scanner.py
`https` will not work on port 80: `ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1076)`

`req.content` should be `req._content` or `req.text`: 
```
if ("global") in req.content: # each smb.conf will contain a [global] variable
TypeError: a bytes-like object is required, not 'str'
```